Ulaznicar/Models/Dogadjaj.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Dogadjaj
    {
        public Dogadjaj()
        {
            this.Kazaliste = new HashSet<Kazaliste>();
            this.Klub = new HashSet<Klub>();
            this.Koncert = new HashSet<Koncert>();
            this.CijenaKarte = new HashSet<CijenaKarte>();
            this.Karta = new HashSet<Karta>();
        }
    
        public int Id { get; set; }
        public string naziv { get; set; }

        [DataType(DataType.DateTime)]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy. HH:mm}", ApplyFormatInEditMode = true)]
        public System.DateTime datum { get; set; }
        public int IdLokacija { get; set; }
        public int brojmjesta { get; set; }
        public byte[] plakat { get; set; }
    
        public virtual Lokacija Lokacija { get; set; }
        public virtual ICollection<Kazaliste> Kazaliste { get; set; }
        public virtual ICollection<Klub> Klub { get; set; }
        public virtual ICollection<Koncert> Koncert { get; set; }
        public virtual ICollection<CijenaKarte> CijenaKarte { get; set; }
        public virtual ICollection<Karta> Karta { get; set; }
    }
}

Ulaznicar/Controllers/DogadjajController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ulaznicar.Models;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Data.Entity.Infrastructure;
using System.Globalization;

namespace Ulaznicar.Controllers
{
    public class DogadjajController : Controller
    {
        private bazaUlazniceEntities db = new bazaUlazniceEntities();

        // GET: Dogadjaj
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string search)
        {
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            ViewBag.user = userUserName;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NazivSortParm = String.IsNullOrEmpty(sortOrder) ? "naziv_asc" : "";
            ViewBag.DatumSortParm = sortOrder == "Date" ? "Date" : "date_desc";
            ViewBag.LokSortParm = String.IsNullOrEmpty(sortOrder) ? "lok_desc" : "";

            var dogadjaj = db.Dogadjaj.Where(s => s.datum >= DateTime.Now).Include(d => d.Lokacija);

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                switch (search)
                {
                    case "Lokacija":
                        dogadjaj = dogadjaj.Where(s => s.Lokacija.naziv.Contains(searchString));
                        break;
                    case "Datum":
                        try
                        {
                            const DateTimeStyles style = DateTimeStyles.AllowWhiteSpaces;
                            DateTime? result = null;
                            DateTime dt;
                            if (DateTime.TryParseExact(searchString, "dd.MM.yyyy.", CultureInfo.InvariantCulture, style, out dt))
                            {
                                result = dt.Date;
                                var result2 = result.Value.AddDays(1);
                                dogadjaj = (from Dogadjaj in db.Dogadjaj
                                            where Dogadjaj.datum >= result
                                                  && Dogadjaj.datum < result2
                                            select Dogadjaj);
                            }
                        }
                        catch { ViewBag.pogreska = "Krivo ste unjeli datum! Pokušajte ponovno!";}
                        break;
                    default:
                        dogadjaj = dogadjaj.Where(s => s.naziv.Contains(searchString));
                        break;
                }
            }

            switch (sortOrder)
            {
                case "naziv_asc":
                    dogadjaj = dogadjaj.OrderBy(s => s.naziv);
                    break;
                //case "Date":
                //    dogadjaj = dogadjaj.OrderByDescending(s => s.datum);
                //    break;
                case "date_desc":
                    dogadjaj = dogadjaj.OrderByDescending(s => s.datum);
                    break;
                case "lok_desc":
                    dogadjaj = dogadjaj.OrderByDescending(s => s.Lokacija.naziv);
                    break;
                default:  // Name ascending 
                    dogadjaj = dogadjaj.OrderBy(s => s.datum);
                    break;
            }

            int pageSize = 10;
            int pageNumber = (page ?? 1);

            if (dogadjaj.Count() == 0)
            {
                ViewBag.rezultat = "Nema događaja koji odgovaraju kriteriju '" + searchString + "'. Pokušajte sa drugačijim pojmom.";
            }

            return View(dogadjaj.ToPagedList(pageNumber, pageSize));
        }

        // GET: Dogadjaj/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dogadjaj dogadjaj = db.Dogadjaj.Find(id);
            ViewBag.cijene = db.CijenaKarte.Where(x => x.IdDogadjaj == id);
            if (dogadjaj == null)
            {
                return HttpNotFound();
            }
            return View(dogadjaj);
        }

        // GET: Dogadjaj/Create
        public ActionResult Create()
        {
            ViewBag.IdLokacija = new SelectList(db.Lokacija, "Id", "naziv");
            return View();
        }

        // POST: Dogadjaj/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HttpPostedFileBase upload, [Bind(Include = "Id,naziv,datum,IdLokacija,brojmjesta,plakat")] Dogadjaj dogadjaj)
        {
             try
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        dogadjaj.plakat = reader.ReadBytes(upload.ContentLength);
                    }
                }
                if (ModelState.IsValid)
                {
                    db.Dogadjaj.Add(dogadjaj);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.IdLokacija = new SelectList(db.Lokacija, "Id", "naziv", dogadjaj.IdLokacija);
            }
             catch (RetryLimitExceededException /* dex */  )
             {
                 //Log the error (uncomment dex variable name and add a line here to write a log.
                 ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
             }
            return View(dogadjaj);
        }

        // GET: Dogadjaj/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dogadjaj dogadjaj = db.Dogadjaj.Find(id);
            if (dogadjaj == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdLokacija = new SelectList(db.Lokacija, "Id", "naziv", dogadjaj.IdLokacija);
            return View(dogadjaj);
        }

        // POST: Dogadjaj/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,naziv,datum,IdLokacija,brojmjesta,plakat")] Dogadjaj dogadjaj, HttpPostedFileBase upload)
        {
            if (upload == null)
            {
                var dogadjaji = (db.Dogadjaj.AsNoTracking().Where(x => x.Id == dogadjaj.Id));
                dogadjaj.plakat = dogadjaji.FirstOrDefault(x => x.Id == dogadjaj.Id).plakat;
            }
            if (ModelState.IsValid)
            {
                if (upload != null && upload.ContentLength > 0)
                {
                    using (var reader = new System.IO.BinaryReader(upload.InputStream))
                    {
                        dogadjaj.plakat = reader.ReadBytes(upload.ContentLength);
                    }
                }

                db.Entry(dogadjaj).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdLokacija = new SelectList(db.Lokacija, "Id", "naziv", dogadjaj.IdLokacija);
            return View(dogadjaj);
        }

        // GET: Dogadjaj/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dogadjaj dogadjaj = db.Dogadjaj.Find(id);
            if (dogadjaj == null)
            {
                return HttpNotFound();
            }
            return View(dogadjaj);
        }

        // POST: Dogadjaj/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dogadjaj dogadjaj = db.Dogadjaj.Find(id);
            db.Dogadjaj.Remove(dogadjaj);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Show(int id)
        {
            var plakat = db.Dogadjaj.Find(id).plakat; 
            if (plakat == null)
            {
                return base.File("~/Content/noimage.png", "image/png");
            }

            return new FileContentResult(plakat, "img");
        }
        
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Ulaznicar/Views/Dogadjaj/Create.cshtml
@model Ulaznicar.Models.Dogadjaj

@{
    ViewBag.Title = "Stvori novi događaj";
}

<h2>Stvori novi događaj</h2>


@using (Html.BeginForm("Create", "Dogadjaj", null, FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.Label("Naziv", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Datum", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLokacija, "Lokacija", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLokacija", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLokacija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Broj mjesta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.brojmjesta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brojmjesta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Plakat", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="plakat" name="upload" />
                @Html.ValidationMessageFor(model => model.plakat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pohrani u bazu" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Natrag na popis", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ulaznicar/Views/Dogadjaj/Delete.cshtml
@model Ulaznicar.Models.Dogadjaj

@{
    ViewBag.Title = "Delete";
}

<h2>Brisanje događaja</h2>

<h3>Jeste li sigurni da želite ukloniti zapis?</h3>
<div>
    <h4>Dogadjaj</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Naziv
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naziv)
        </dd>

        <dt>
            Datum održavanja
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datum)
        </dd>

        <dt>
            Broj mjesta
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brojmjesta)
        </dd>

        <dt>
            Plakat
        </dt>

        <dd>
            <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = Model.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
        </dd>

        <dt>
            Adresa lokacije
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokacija.adresa)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Izbriši" class="btn btn-default" /> |
            @Html.ActionLink("Povratak na popis događaja", "Index")
        </div>
    }
</div>

Ulaznicar/Views/Dogadjaj/Details.cshtml
@model Ulaznicar.Models.Dogadjaj

@{
    ViewBag.Title = "Detalji";
}
@using Microsoft.AspNet.Identity
<h2>Detalji</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Plakat
        </dt>

        <dd>
            <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = Model.Id })" style="max-height:200px; max-width:200px; border-radius:10px" />
        </dd>
        <dt>
            Naziv
        </dt>

        <dd>
            @Html.DisplayFor(model => model.naziv)
        </dd>

        <dt>
            Datum
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datum)
        </dd>

        <dt>
            Broj mjesta
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brojmjesta)
        </dd>
        <dt>
            Naziv lokacije
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokacija.naziv)
        </dd>
        <dt>
            Adresa
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Lokacija.adresa)
        </dd>
    </dl>
</div>
<table class="table">
    <tr>
        <th>
        Ime kategorije karte
        </th>
        <th>
            Cijena
        </th>
        <th></th>
    </tr>
    @if (ViewBag.cijene != null)
    {
        foreach (var cijena in ViewBag.cijene)
        {
            <tr>
                <td>@cijena.VrstaKarte.imekategorije</td>
                <td>@cijena.cijena</td>
                <td>
                    @Html.ActionLink("Kupi!", "Create", "Karta", new { id = Model.Id, idcijena = cijena.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>

        }
    }
</table>
    <p>
        @if (User.Identity.GetUserName() == "ADMIN")
        {
            @Html.ActionLink("Ažuriraj", "Edit", new { id = Model.Id })
        }
    </p>
    <p>@Html.ActionLink("Povratak na popis događaja", "Index")</p>

Ulaznicar/Views/Dogadjaj/Edit.cshtml
@model Ulaznicar.Models.Dogadjaj

@{
    ViewBag.Title = "Ažuriraj";
}

<h2>Ažuriraj</h2>


@using (Html.BeginForm("Edit", "Dogadjaj", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Dogadjaj</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.naziv,"Naziv", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naziv, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naziv, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.datum,"Datum održavanja", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.datum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.datum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IdLokacija, "Lokacija", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdLokacija", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdLokacija, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.brojmjesta, "Broj slobodnih mjesta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.brojmjesta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.brojmjesta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2">Plakat</label>
            <div class="col-md-10">
                <input type="file" id="image" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ažuriraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Povratak na popis događaja", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ulaznicar/Views/Dogadjaj/Index.cshtml
@model PagedList<Ulaznicar.Models.Dogadjaj>
@using PagedList.Mvc;
@using PagedList;
@using Microsoft.AspNet.Identity
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />


@*@model IEnumerable<Ulaznicar.Models.Dogadjaj>*@

@{
    ViewBag.Title = "Popis događaja";
}

<h2>Događaji</h2>

@if (ViewBag.user == "ADMIN") 
{ 
<p>
    @Html.ActionLink("Dodaj novi događaj", "Create")
</p>
}
@using (Html.BeginForm())
{
    <p>
        Pretraži : @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Pretraži" />
    </p>
    <div class="form-group">
        <div class="radio-inline">
            @Html.RadioButton("search", "Dogadjaj", true,
          new { id = "Dogadjaj" }) po događaju
        </div>
        <div class="radio-inline">
            @Html.RadioButton("search", "Lokacija",
           new { id = "Lokacija" }) po lokaciji
        </div>
        <div class="radio-inline">
            @Html.RadioButton("search", "Datum",
           new { id = "Datum" }) po datumu
        </div>
    </div>
}
@if (ViewBag.pogreska != null)
{
    <h3 style="color:red">@ViewBag.pogreska</h3>
}
@if (ViewBag.rezultat != null)
{
    <h3 style="color:darkblue">@ViewBag.rezultat</h3>
}

<table class="table">
    <tr>
        <th>
            Plakat
        </th>
        <th>
            @Html.ActionLink("Naziv", "Index", new { sortOrder = ViewBag.NazivSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Datum održavanja", "Index", new { sortOrder = ViewBag.DatumSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Lokacija", "Index", new { sortOrder = ViewBag.LokSortParm, currentFilter=ViewBag.CurrentFilter })
        </th>
        <th>
            Broj mjesta
        </th>


        <th></th>
    </tr>

    @foreach (var item in Model)
{
        <tr>
            <td>
                <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = item.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lokacija.naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.brojmjesta)
            </td>
           
            <td>
                @if (ViewBag.user == "ADMIN")
                {
                    <p>
                        @Html.ActionLink("Ažuriraj", "Edit", new { id = item.Id }, new { @class = "btn btn-default" })
                    </p>
                    <p>
                        @Html.ActionLink("Izbriši", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                    </p>
                }
                @if (Request.IsAuthenticated)
                {
                    <p>
                        @Html.ActionLink("Detalji", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
                    </p>
                    <p>
                        @Html.ActionLink("Kupi ulaznicu!", "Create", "Karta", new { id = item.Id }, new { @class = "btn btn-success" })
                    </p>
                }
            </td>
            </tr>
}

        </table>
<div class="col-sm-10">
    <div class="center">
        <br />
        Stranica @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) od @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div>