Ulaznicar/Models/Karta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Karta
    {
        public Karta()
        {
            this.KupljeneKarte = new HashSet<KupljeneKarte>();
        }
    
        public int Id { get; set; }
        public int IdDogadjaj { get; set; }
        public int IdCijena { get; set; }
        public string zastitnikod { get; set; }
        public byte[] QR_KOD { get; set; }
        public Nullable<int> brojkarte { get; set; }
    
        public virtual CijenaKarte CijenaKarte { get; set; }
        public virtual Dogadjaj Dogadjaj { get; set; }
        public virtual ICollection<KupljeneKarte> KupljeneKarte { get; set; }
    }
}

Ulaznicar/Controllers/KartaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Ulaznicar.Models;
using Gma.QrCodeNet.Encoding;
using Gma.QrCodeNet.Encoding.Windows.Controls;
using System.Drawing;
using System.Drawing.Imaging;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.IO;
using PagedList;
using Rotativa;
using System.ComponentModel;

namespace Ulaznicar.Controllers
{
    
    public class KartaController : Controller
    {
        bazaUlazniceEntities context = new bazaUlazniceEntities();
        // GET: Karta
        public ActionResult Index(string sortOrder, string currentFilter, int? page)
        {
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            var id = (context.Korisnik.Where(x => x.korisnickoime == userUserName).First()).Id;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NazivSortParm = String.IsNullOrEmpty(sortOrder) ? "naziv_desc" : "naziv_asc";
            ViewBag.DatumSortParm = sortOrder == "Date" ? "Date" : "date_asc";
            ViewBag.LokSortParm = String.IsNullOrEmpty(sortOrder) ? "lok_desc" : "";

            var burza = context.Burza;

            var kupljene = context.KupljeneKarte.Where(x => x.IdKorisnik == id);
            List<Karta> karte = new List<Karta>();

            foreach (var kup in kupljene)
            {
                karte.Add(context.Karta.Where(x=>x.Id == kup.IdKarta).Include(x=>x.Dogadjaj.Lokacija).Single());
                ViewData[kup.IdKarta.ToString()] = kup.Id;
                var naburzi = burza.Where(x => x.IdKarta == kup.Id).SingleOrDefault();
                if (naburzi != null && naburzi.IdKupac == null)
                {
                    ViewData[kup.Karta.zastitnikod] = naburzi.Id;
                }
            }
            int pageSize = 5;
            int pageNumber = (page ?? 1);

            var poredane = karte.OrderByDescending(x => x.Dogadjaj.datum);

            switch (sortOrder)
            {
                case "naziv_desc":
                    poredane = karte.OrderByDescending(x => x.Dogadjaj.naziv);
                    break;
                case "naziv_asc":
                    poredane = karte.OrderBy(x => x.Dogadjaj.naziv);
                    break;
                case "date_asc":
                    poredane = karte.OrderBy(x => x.Dogadjaj.datum);
                    break;
                case "lok_desc":
                    poredane = karte.OrderByDescending(x => x.Dogadjaj.Lokacija.naziv);
                    break;
                default:  // date descending
                    break;
            }


            return View(poredane.ToPagedList(pageNumber, pageSize));
        }

        // GET: Karta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Karta karta = context.Karta.Find(id);
            ViewBag.kup = context.KupljeneKarte.FirstOrDefault(x => x.IdKarta == id).Id;
            if (karta == null)
            {
                return HttpNotFound();
            }
            return View(karta);
        }

        // GET: Karta/Create
        public ActionResult Create(int id, int? idcijena)
        {
            var dogadjaj = context.Dogadjaj.Find(id);
            var brojevnostanje = (context.Karta.Where(x => x.IdDogadjaj == id)).Max(x => x.brojkarte);
            if (brojevnostanje == null)
            {
                brojevnostanje = 0;
            }
            try
            {

                if (idcijena == null)
                {
                    var cijena = context.CijenaKarte.Where(x => x.IdDogadjaj == id);

                    if (cijena.Count(x => x.IdDogadjaj == id) == 1)
                    {
                        idcijena = cijena.First(x => x.IdDogadjaj == id).Id;
                    }
                    else
                    {
                        ModelState.AddModelError("", "Niste odabrali koju vrstu ulaznice želite!");
                        return RedirectToAction("Details", "Dogadjaj", new { id = id });
                    }
                }

                //provjera da nije vec stvorena karta, a da je netko odustao od kupovine
                var kupljene = context.KupljeneKarte;
                var karte = context.Karta.Where(x => x.IdDogadjaj == id);
                foreach (var kart in karte)
                {
                    if (kupljene.FirstOrDefault(x => x.IdKarta == kart.Id) == null && kart.IdCijena == idcijena)
                    {
                        return RedirectToAction("Kupovina", new { id = kart.Id });
                    }
                }

                if (dogadjaj.brojmjesta > 0)
                {
                    string zastitni = (dogadjaj.naziv + " " + id.ToString() + " " + (brojevnostanje + 1).ToString()).GetHashCode().ToString();
                    QrEncoder qrEncoder = new QrEncoder(ErrorCorrectionLevel.H);
                    QrCode qrCode = qrEncoder.Encode(zastitni);

                    Renderer renderer = new Renderer(5, Brushes.Black, Brushes.White);
                    Stream memoryStream = new MemoryStream();
                    renderer.WriteToStream(qrCode.Matrix, memoryStream, ImageFormat.Png);

                    memoryStream.Position = 0;
                    byte[] kod = ((MemoryStream)memoryStream).ToArray();

                    Karta novaKarta = new Karta
                    {
                        zastitnikod = zastitni,
                        IdDogadjaj = id,
                        QR_KOD = kod,
                        brojkarte = brojevnostanje + 1,
                        IdCijena = (int)idcijena
                    };

                    context.Karta.Add(novaKarta);
                    dogadjaj.brojmjesta -= 1;
                    context.Entry(dogadjaj).State = EntityState.Modified;
                    context.SaveChanges();

                    //moguće jer nakon populiranja objekta u bazu, savechanges vrati ID u naš ovdje objekt :3
                    return RedirectToAction("Kupovina", new { id = novaKarta.Id });
                }
            }
            catch
            {

                return RedirectToAction("Details", "Dogadjaj", new { id = id });
            }
            return RedirectToAction("Details", "Dogadjaj", new { id = id });
        }

        // GET: Karta/Edit/5
        public ActionResult Pokloni(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();

            var kupljena = context.KupljeneKarte.Find(id);
            if (kupljena == null)
            {
                return HttpNotFound();
            }
            var odabran = kupljena.Karta.Dogadjaj;

            ViewBag.naziv = odabran.naziv;
            ViewBag.lok = odabran.Lokacija.naziv;
            ViewBag.dat = odabran.datum;
            ViewBag.cijena = kupljena.Karta.CijenaKarte.VrstaKarte.imekategorije;

            ViewBag.IdKorisnik = new SelectList(context.Korisnik.Where(x=>x.korisnickoime != userUserName), "Id", "korisnickoime");


            return View(kupljena);
        }

        // POST: Karta/Edit/5
        [HttpPost]
        public ActionResult Pokloni([Bind(Include = "Id,IdKorisnik,IdKarta")] KupljeneKarte kupljenakarta)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    context.Entry(kupljenakarta).State = EntityState.Modified;
                    context.SaveChanges();
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Pokloni", new {id = kupljenakarta.Id});
            }
        }

        public ActionResult Kupovina(int id)
        {
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            
            var karta = context.Karta.Find(id);

            ViewBag.naziv = karta.Dogadjaj.naziv;
            ViewBag.datum = karta.Dogadjaj.datum;
            ViewBag.mjesto = karta.Dogadjaj.Lokacija.naziv;
            ViewBag.adresa = karta.Dogadjaj.Lokacija.adresa;
            ViewBag.cijena = karta.CijenaKarte.cijena;
            ViewBag.korisnik = userUserName;

            return View(karta);
        }

        public ActionResult Kupovina_konacna(int id)
        {
            try
            {
                var userId = User.Identity.GetUserId();
                var userUserName = User.Identity.GetUserName();
                var korisnik = (context.Korisnik.Where(x => x.korisnickoime == userUserName).First()).Id;

                KupljeneKarte karta = new KupljeneKarte
                {
                    IdKarta = id,
                    IdKorisnik = korisnik
                };

                context.KupljeneKarte.Add(karta);
                context.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return RedirectToAction("Kupovina");
            }
        }


        //public ActionResult KartazaIspis(int invoiceId)
        //{
        //    var invoiceViewModel;
        //    // code to retrieve data from a database
        //    return View(invoiceViewModel);
        //}
        //public ActionResult Ispis(int invoiceId)
        //{
        //    return new ActionAsPdf(
        //                   "Invoice",
        //                   new { invoiceId = invoiceId }) { FileName = "Invoice.pdf" };

Ulaznicar/Views/Karta/Details.cshtml
@model Ulaznicar.Models.Karta

@{
    ViewBag.Title = "Detalji";
}

<h2>Detalji</h2>

<div>
    <h4>Ulaznica</h4>
    <hr />
    <dl class="dl-horizontal">
        @if (Model.Dogadjaj.datum <= DateTime.Today)
        {
            <dt>
                QR kod ulaznice :
            </dt>

            <dd>
                @*<img id="the-image" src="@Url.Action("Show", "Karta", new { id = Model.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />*@
                <img src="@Url.Action("Show", "Karta", new { id = Model.Id })" alt="image" />
            </dd>
        }
        else
        {
            <dd>
                <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = Model.Dogadjaj.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
            </dd>
        }
        <dt>
            Naziv događaja :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dogadjaj.naziv)
        </dd>
        <dt>
            Naziv lokacije :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dogadjaj.Lokacija.naziv)
        </dd>
        <dt>
            Adresa lokacije :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dogadjaj.Lokacija.adresa)
        </dd>
        <dt>
            Vrsta ulaznice :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CijenaKarte.VrstaKarte.imekategorije)
        </dd>
        <dt>
            Cijena :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CijenaKarte.cijena)
        </dd>

        <dt>
            Broj ulaznice :
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brojkarte)
        </dd>



    </dl>
</div>
<p>
@if (Model.Dogadjaj.datum >= DateTime.Now)
        {
    @Html.ActionLink("Stavi na burzu", "Create", "Burza", new { id = Model.Dogadjaj.Id}, new { @class = "btn btn-success" }) 
}
    @Html.ActionLink("Pokloni", "Pokloni", new { id = ViewBag.kup }, new { @class = "btn btn-primary" }) 
    </p>
<p>
    @Html.ActionLink("Povratak na moje ulaznice", "Index")
</p>

Ulaznicar/Views/Karta/Index.cshtml
@model PagedList<Ulaznicar.Models.Karta>
@using PagedList.Mvc;
@using PagedList;
@using Microsoft.AspNet.Identity
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Moje ulaznice";
}

<h2>Moje ulaznice</h2>

<p>
    @Html.ActionLink("Kupi novu", "Index", "Dogadjaj")
</p>
<table class="table">
    <tr>
        <th>
            QR kod ulaznice
        </th>
        <th>
            @Html.ActionLink("Naziv događaja", "Index", new { sortOrder = ViewBag.NazivSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Lokacija", "Index", new { sortOrder = ViewBag.LokSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Datum održavanja", "Index", new { sortOrder = ViewBag.DatumSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Cijena
        </th>

        <th>
            Vrsta ulaznice
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        
        <td>
            @if (item.Dogadjaj.datum <= DateTime.Today)
            {
                <img id="the-image" src="@Url.Action("Show", "Karta", new { id = item.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
            }
            else
            {
                <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = item.Dogadjaj.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
            }
        </td>


       
        <td>
            @Html.DisplayFor(modelItem => item.Dogadjaj.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dogadjaj.Lokacija.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Dogadjaj.datum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CijenaKarte.cijena)
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.CijenaKarte.VrstaKarte.imekategorije)
        </td>
        <td>
            @if (item.Dogadjaj.datum > DateTime.Now)
            {
                if (ViewData[item.zastitnikod] != null)
                {
                    <p>
                        @Html.ActionLink("Ukloni s burze", "Delete", "Burza", new { id = ViewData[item.zastitnikod] }, new { @class = "btn btn-danger" })
                    </p>
                }
                else
                {
                <p>
                    @Html.ActionLink("Stavi na burzu", "Create", "Burza", new { id = item.Id }, new { @class = "btn btn-success" })
                </p>
                }
            }
            <p>
                @Html.ActionLink("Detalji", "Details", new { id = item.Id }, new { @class = "btn btn-info" })
            </p>
            <p>
                @Html.ActionLink("Pokloni prijatelju", "Pokloni", new { id = ViewData[item.Id.ToString()] }, new { @class = "btn btn-primary" })
            </p>
        </td>
    </tr>
}

</table>
<div class="col-sm-10">
    <div class="center">
        <br />
        Stranica @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) od @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div>

Ulaznicar/Views/Karta/Ispis.cshtml
@model Ulaznicar.Models.Karta

<div>
    <h4>Karta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.zastitnikod)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.zastitnikod)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QR_KOD)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QR_KOD)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.brojkarte)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.brojkarte)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CijenaKarte.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CijenaKarte.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Dogadjaj.naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Dogadjaj.naziv)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Ulaznicar/Views/Karta/Kupovina.cshtml
@model Ulaznicar.Models.Karta

@{
    ViewBag.Title = "Kupovina";
}
<div>
<h2>Kupovina</h2>
    <div >
        <h3 >
            Trenutno ste prijavljeni kao :
        </h3>
        <h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;@Html.ViewBag.korisnik</h1>
    </div>
<dl class="dl-horizontal" style="font-size:medium; background-color:aliceblue">
    <dt>
        Naziv događaja :
    </dt>

    <dd>
        @Html.ViewBag.naziv
    </dd>
    <dt>
        Datum događaja :
    </dt>

    <dd>
        @Html.ViewBag.datum
    </dd>
    <dt>
        Lokacija :
    </dt>

    <dd>
        @Html.ViewBag.mjesto
    </dd>
    <dt>
        Adresa lokacije :
    </dt>

    <dd>
        @Html.ViewBag.adresa
    </dd>

    <dt>
        Cijena :
    </dt>

    <dd>
        @Html.ViewBag.cijena
    </dd>
</dl>
</div>

<div><h2>Unesite broj računa kojim želite platiti ulaznicu: </h2>
    <input type="text" id="text" name="brrac" />

    &nbsp; &nbsp; &nbsp; @Html.ActionLink("Kupi ulaznicu", "Kupovina_konacna", "Karta", new { id = Model.Id }, new { @class = "btn btn-success" })

    <p style="padding-top:20px">
        @Html.ActionLink("Odustani od kupovine", "Index", "Dogadjaji", null, new { @class = "btn btn-danger" })
    </p>

</div>
    

Ulaznicar/Views/Karta/Pokloni.cshtml
@model Ulaznicar.Models.KupljeneKarte

@{
    ViewBag.Title = "Pokloni";
}

<h2>Pokloni</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pokloni ulaznicu korisniku : </h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@
        @Html.HiddenFor(model => model.IdKarta)

        @*<div class="form-group">
            @Html.LabelFor(model => model.IdKarta, "IdKarta", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdKarta", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKarta, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group" style="font-size:medium">
            @Html.Label("Odabrana ulaznica", htmlAttributes: new { @class = "control-label col-md-2 text-primary" })
            <div class="col-md-10">
                <p>@Html.ViewBag.naziv</p>
                <p>@Html.ViewBag.lok</p>
                <p>@Html.ViewBag.dat</p>
                <p>@Html.ViewBag.cijena</p>

            </div>
        </div>


        <div class="form-group" style="font-size:medium">
            @Html.LabelFor(model => model.IdKorisnik, "Korisničko ime", htmlAttributes: new { @class = "control-label col-md-2 text-primary" })
            <div class="col-md-10">
                @Html.DropDownList("IdKorisnik", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IdKorisnik, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Pokloni" class="btn btn-primary"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Vrati se na moje ulaznice", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}