Ulaznicar/Models/Burza.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ulaznicar.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Burza
    {
        public int Id { get; set; }
        public Nullable<int> IdKupac { get; set; }
        public int IdKarta { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public System.DateTime datumponude { get; set; }

        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy HH:mm}")]
        public Nullable<System.DateTime> datumprodaje { get; set; }
        public decimal cijena { get; set; }
    
        public virtual KupljeneKarte KupljeneKarte { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}

Ulaznicar/Controllers/BurzaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using System.Data.Entity.Infrastructure;
using Ulaznicar.Models;
using System.Globalization;

namespace Ulaznicar.Controllers
{
    public class BurzaController : Controller
    {
        private bazaUlazniceEntities db = new bazaUlazniceEntities();

        // GET: Burza
        public ActionResult Index(string sortOrder, string currentFilter, string searchString, int? page, string search)
        {
            var burza = db.Burza.Include(b => b.Korisnik).Where(b=>b.IdKupac == null);

            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            var korisnik = db.Korisnik.First(k => k.korisnickoime == userUserName);

            //provjeravamo ima li korisnik neku svoju kartu već na burzi, te mu želimo omogućiti da ju može maknuti
            var kupljene = db.KupljeneKarte.Where(x => x.IdKorisnik == korisnik.Id).Include(b=>b.Karta.Dogadjaj);
            List<int> karte = new List<int>();

            foreach (var kup in kupljene)
            {
                if (burza.FirstOrDefault(x => x.IdKarta == kup.Id) != null)
                {
                    karte.Add(kup.Id);
                }
            }
            ViewBag.vlastite = karte;
            ViewBag.user = userUserName;

            ViewBag.CurrentSort = sortOrder;
            ViewBag.NazivSortParm = String.IsNullOrEmpty(sortOrder) ? "naziv_desc" : "";
            ViewBag.DatumSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.CijenaSortParm = String.IsNullOrEmpty(sortOrder) ? "cijena_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            if (!String.IsNullOrEmpty(searchString))
            {
                switch (search)
                {
                    case "Lokacija":
                        burza = burza.Where(s => s.KupljeneKarte.Karta.Dogadjaj.Lokacija.naziv.Contains(searchString));
                        break;
                    case "Datum":
                        try
                        {
                            const DateTimeStyles style = DateTimeStyles.AllowWhiteSpaces;
                            DateTime? result = null;
                            DateTime dt;
                            if (DateTime.TryParseExact(searchString, "dd.MM.yyyy.", CultureInfo.InvariantCulture, style, out dt))
                            {
                                result = dt.Date;
                                var result2 = result.Value.AddDays(1);
                                burza = (from Burza in db.Burza
                                            where Burza.datumponude >= result
                                                  && Burza.datumponude < result2
                                         select Burza);
                            }
                        }
                        catch { ViewBag.pogreska = "Krivo ste unjeli datum! Pokušajte ponovno!"; }
                        break;
                    default:
                        burza = burza.Include(x => x.KupljeneKarte.Karta.Dogadjaj).Where(
                            s => s.KupljeneKarte.Karta.Dogadjaj.naziv.Contains(searchString));
                        break;
                }
            }
            
            switch (sortOrder)
            {
                case "naziv_desc":
                    burza = burza.OrderByDescending(s => s.KupljeneKarte.Karta.Dogadjaj.naziv);
                    break;
                case "Date":
                    burza = burza.OrderByDescending(s => s.datumponude);
                    break;
                case "date_desc":
                    burza = burza.OrderByDescending(s => s.datumponude);
                    break;
                case "cijena_desc":
                    burza = burza.OrderByDescending(s => s.cijena);
                    break;
                default:  // Name ascending 
                    burza = burza.OrderBy(s => s.datumponude);
                    break;
            }

            int pageSize = 15;
            int pageNumber = (page ?? 1);

            return View(burza.ToPagedList(pageNumber, pageSize));

        }

        // GET: Burza/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Burza burza = db.Burza.Find(id);
            if (burza == null)
            {
                return HttpNotFound();
            }
            return View(burza);
        }

        // GET: Burza/Create
        public ActionResult Create(int? id)
        {
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            var korisnik = db.Korisnik.First(k => k.korisnickoime == userUserName);
            var postojeci = db.Burza;

            if (id != null)
            {
                var kupljena = db.KupljeneKarte.Where(x => x.IdKarta == id).Include(x => x.Karta).Single();
                var provjera = postojeci.FirstOrDefault(x=>x.IdKarta == kupljena.Id);
                if (provjera == null || provjera.IdKupac != null)
                {
                    var dogadjaj = db.Dogadjaj.Find(kupljena.Karta.IdDogadjaj);
                    ViewBag.cijena = kupljena.Karta.CijenaKarte.cijena;
                    ViewBag.dogadjaj = dogadjaj;
                    ViewBag.ime = id;
                    return View();
                }
                return RedirectToAction("Index");
            }

                var kupljenekarte = db.KupljeneKarte.Where(kar => kar.IdKorisnik == korisnik.Id).Include(x => x.Karta);
                List<Dogadjaj> dogadjaji = new List<Dogadjaj>();

                foreach (var karta in kupljenekarte)
                {
                    //provjera je li karta stara i je li već postavljena na burzu
                    var provjera = postojeci.FirstOrDefault(x=>x.IdKarta == karta.Id);
                    if (karta.Karta.Dogadjaj.datum >= DateTime.Now && (provjera == null || provjera.IdKupac != null))
                    {
                        dogadjaji.Add(karta.Karta.Dogadjaj);
                    }
                }

                ViewBag.IdKarta = new SelectList(dogadjaji, "Id", "naziv");

            return View();
        }

        // POST: Burza/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,IdKupac,IdKarta,datumponude,datumprodaje,cijena")] Burza burza)
        {
            var userId = User.Identity.GetUserId();
            var userUserName = User.Identity.GetUserName();
            var korisnik = db.Korisnik.AsNoTracking().First(k => k.korisnickoime == userUserName).Id;
            var Idd = burza.IdKarta;

            var idkarte = db.KupljeneKarte.AsNoTracking().Where(
                x => x.IdKorisnik == korisnik).Include(x => x.Karta).FirstOrDefault(
                x => x.Karta.Dogadjaj.Id == Idd
                ).Id;


            burza.IdKarta = idkarte;
            burza.datumponude = DateTime.Now;
            if (burza.Id != 0)
            {
                burza.Id = 0;
            }

            try
            {
                db.Burza.Add(burza);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                var kupljenekarte = db.KupljeneKarte.Where(kar => kar.IdKorisnik == korisnik).Include(x => x.Karta);
                List<Dogadjaj> dogadjaji = new List<Dogadjaj>();

                foreach (var karta in kupljenekarte)
                {
                    dogadjaji.Add(karta.Karta.Dogadjaj);
                }

                ViewBag.IdKarta = new SelectList(dogadjaji, "Id", "naziv", Idd);
                return View(burza);
            }
        }

        // GET: Burza/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Burza burza = db.Burza.Find(id);
            if (burza == null)
            {
                return HttpNotFound();
            }
            ViewBag.IdKupac = new SelectList(db.Korisnik, "Id", "korisnickoime", burza.IdKupac);
            return View(burza);
        }

        // POST: Burza/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,IdKupac,IdKarta,datumponude,datumprodaje,cijena")] Burza burza)
        {
            if (ModelState.IsValid)
            {
                db.Entry(burza).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.IdKupac = new SelectList(db.Korisnik, "Id", "korisnickoime", burza.IdKupac);
            return View(burza);
        }

        // GET: Burza/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

Ulaznicar/Views/Burza/Create.cshtml
@model Ulaznicar.Models.Burza

@{
    ViewBag.Title = "Ponuda";
}

<h2>Ponudi ulaznicu na burzi</h2>


@*@using (Html.BeginForm("Create", "Burza", null, FormMethod.Post, new { enctype = "multipart/form-data" }))*@
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Burza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdKupac)
        @Html.HiddenFor(model => model.datumponude)
        @Html.HiddenFor(model => model.datumprodaje)


        @if (ViewBag.ime != null)
        {
            <div class="form-group" style="font-size:medium">
                @Html.Label("Naziv događaja", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <p>@Html.ViewBag.dogadjaj.naziv</p>
                </div>
            </div>
        <div class="form-group" style="font-size:medium">
            @Html.Label("Naziv lokacije", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p>@Html.ViewBag.dogadjaj.Lokacija.naziv</p>
            </div>
        </div>
        <div class="form-group" style="font-size:medium">
            @Html.Label("Datum održavanja", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <p> @Html.ViewBag.dogadjaj.datum</p>
            </div>
        </div>
    <div class="form-group" style="font-size:medium">
        @Html.Label("Kupljena po cijeni", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <p> @Html.ViewBag.cijena</p>
        </div>
    </div>


            @*@Html.Hidden("IdKarta",ViewData["karta"])*@
            @Html.Hidden("Id", 0)
            @Html.Hidden("IdKarta", (int)ViewBag.dogadjaj.Id)
        }
        else
        {
            <div class="form-group">
                @Html.LabelFor(model => model.IdKarta, "Ulaznica za događaj", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("IdKarta", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.IdKarta, "", new { @class = "text-danger" })
                </div>
            </div>

        }
        <div class="form-group">
            @Html.LabelFor(model => model.cijena, "Cijena", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cijena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cijena, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Postavi na burzu!" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ulaznicar/Views/Burza/Delete.cshtml
@model Ulaznicar.Models.Burza

@{
    ViewBag.Title = "Brisanje";
}

<h2>Brisanje</h2>

<h3>Jeste li sigurni da želite ukloniti zapis?</h3>
<div>
    <h4>Burza</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Događaj
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KupljeneKarte.Karta.Dogadjaj.naziv)
        </dd>

        <dt>
            Datum ponude
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumponude)
        </dd>

        <dt>
            Datum prodaje
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumprodaje)
        </dd>

        <dt>
            Cijena
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cijena)
        </dd>

        <dt>
            Kupac
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Korisnik.korisnickoime)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ukloni s burze" class="btn btn-default" /> |
            @Html.ActionLink("Povratak na burzu", "Index")
        </div>
    }
</div>

Ulaznicar/Views/Burza/Details.cshtml
@model Ulaznicar.Models.Burza

@{
    ViewBag.Title = "Detalji";
}

<h2>Detalji</h2>

<div>
    <h4>Burza</h4>
    <hr />
    <dl class="dl-horizontal">
         <dt>
            Plakat
        </dt>
            
        <dd>
            <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = Model.KupljeneKarte.Karta.Dogadjaj.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
        </dd>
    
        <dt>
            Naziv događaja
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KupljeneKarte.Karta.Dogadjaj.naziv)
        </dd>
        <dt>
            Naziv lokacije
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KupljeneKarte.Karta.Dogadjaj.Lokacija.naziv)
        </dd>
        <dt>
            Adresa lokacije
        </dt>

        <dd>
            @Html.DisplayFor(model => model.KupljeneKarte.Karta.Dogadjaj.Lokacija.adresa)
        </dd>
        
        <dt>
            Datum ponude
        </dt>

        <dd>
            @Html.DisplayFor(model => model.datumponude)
        </dd>

        <dt>
            Cijena
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cijena)
        </dd>


    </dl>
</div>
<p>
    @if (Model.IdKupac == null)
    {
        @Html.ActionLink("Kupi ovu ulaznicu", "Kupovina", new { id = Model.Id }, new { @class = "btn btn-success" })
    }
    @Html.ActionLink("Povratak na burzu", "Index")
</p>

Ulaznicar/Views/Burza/Edit.cshtml
@model Ulaznicar.Models.Burza

@{
    ViewBag.Title = "Ažuriraj";
}

<h2>Ažuriraj</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Burza</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.IdKupac)
        @Html.HiddenFor(model => model.IdKarta)
        @Html.HiddenFor(model => model.datumponude)
        @Html.HiddenFor(model => model.datumprodaje)

        <div class="form-group">
            @Html.LabelFor(model => model.cijena, "Cijena", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cijena, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cijena, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ažuriraj" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Ulaznicar/Views/Burza/Index.cshtml
@model PagedList<Ulaznicar.Models.Burza>
@using PagedList.Mvc;
@using PagedList;
@using Microsoft.AspNet.Identity
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Burza";
}

<h2>Karte na burzi</h2>

<p>
    @Html.ActionLink("Stavi svoju kartu na burzu", "Create")
</p>

@using (Html.BeginForm())
{
    <p>
        Pretraži : @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Pretraži" />
    </p>
    <div class="form-group">
        <div class="radio-inline">
            @Html.RadioButton("search", "Dogadjaj", true,
          new { id = "Dogadjaj" }) po događaju
        </div>
        <div class="radio-inline">
            @Html.RadioButton("search", "Lokacija",
           new { id = "Lokacija" }) po lokaciji
        </div>
        <div class="radio-inline">
            @Html.RadioButton("search", "Datum",
           new { id = "Datum" }) po datumu
        </div>
    </div>
}
<table class="table">
    <tr>
        <th>
            Plakat
        </th>
        <th>
            @Html.ActionLink("Naziv događaja", "Index", new { sortOrder = ViewBag.NazivSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            Lokacija
        </th>
        <th>
            Datum događaja
        </th>

        <th>
            @Html.ActionLink("Datum ponude", "Index", new { sortOrder = ViewBag.DatumSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th>
            @Html.ActionLink("Cijena", "Index", new { sortOrder = ViewBag.CijenaSortParm, currentFilter = ViewBag.CurrentFilter })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            <img id="the-image" src="@Url.Action("Show", "Dogadjaj", new { id = item.KupljeneKarte.Karta.Dogadjaj.Id })" style="max-height:150px; max-width:150px; border-radius:10px" />
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KupljeneKarte.Karta.Dogadjaj.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KupljeneKarte.Karta.Dogadjaj.Lokacija.naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.KupljeneKarte.Karta.Dogadjaj.datum)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.datumponude)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.cijena)
        </td>

        @if (ViewBag.user == "ADMIN")
        {
            <td>

                @Html.ActionLink("Izbriši", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
            </td>
        }
        @if (Request.IsAuthenticated)
        {
         
                if (ViewBag.vlastite.IndexOf(item.IdKarta) != -1)
                {
                    <td>
                        @Html.ActionLink("Ažuriraj", "Edit", new { id = item.Id }, new { @class = "btn btn-default" }) 
                        @Html.ActionLink("Izbriši", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                        </td>
                }
                else
                {
                    if (item.IdKupac == null)
                    {
                        <td>
                            @Html.ActionLink("Detalji", "Details", new { id = item.Id }, new { @class = "btn btn-info" }) 
                            @Html.ActionLink("Kupi ulaznicu!", "Kupovina", new { id = item.Id }, new { @class = "btn btn-success" })
                        </td>
                    }
                }

        }
    </tr>
}

</table>
<div class="col-sm-10">
    <div class="center">
        <br />
        Stranica @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) od @Model.PageCount
        @Html.PagedListPager(Model, page => Url.Action("Index", new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
</div>

Ulaznicar/Views/Burza/Kupovina.cshtml
@model Ulaznicar.Models.Burza

@{
    ViewBag.Title = "Kupovina";
}
<div>
<h2>Kupovina</h2>
    <div >
        <h3 >
            Trenutno ste prijavljeni kao :
        </h3>
        <h1>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;@Html.ViewBag.korisnik</h1>
    </div>
<dl class="dl-horizontal" style="font-size:medium; background-color:aliceblue">
    <dt>
        Naziv događaja :
    </dt>

    <dd>
        @Html.ViewBag.naziv
    </dd>
    <dt>
        Datum događaja :
    </dt>

    <dd>
        @Html.ViewBag.datum
    </dd>
    <dt>
        Lokacija :
    </dt>

    <dd>
        @Html.ViewBag.mjesto
    </dd>
    <dt>
        Adresa lokacije :
    </dt>

    <dd>
        @Html.ViewBag.adresa
    </dd>

    <dt>
        Cijena :
    </dt>

    <dd>
        @Html.ViewBag.cijena
    </dd>
</dl>
</div>

<div><h2>Unesite broj računa kojim želite platiti ulaznicu: </h2>
    <input type="text" id="text" name="brrac" />

    &nbsp; &nbsp; &nbsp; @Html.ActionLink("Kupi ulaznicu", "Kupovina_konacna", "Burza", new { id = Model.Id }, new { @class = "btn btn-success" })

    <p style="padding-top:20px">
        @Html.ActionLink("Odustani od kupovine", "Index", null, new { @class = "btn btn-danger" })
    </p>

</div>
    